export const fontWeights = {
    thin: ['font-thin'],
    'extra-light': ['font-extralight'],
    light: ['font-light'],
    regular: ['font-normal'],
    medium: ['font-medium'],
    'semi-bold': ['font-semibold'],
    bold: ['font-bold'],
    'extra-bold': ['font-extrabold'],
    black: ['font-black'],
    'thin-italic': ['font-thin', 'italic'],
    'extra-light-italic': ['font-extralight', 'italic'],
    'light-italic': ['font-light', 'italic'],
    italic: ['font-normal', 'italic'],
    'regular-italic': ['font-normal', 'italic'],
    'medium-italic': ['font-medium', 'italic'],
    'semi-bold-italic': ['font-semibold', 'italic'],
    'bold-italic': ['font-bold', 'italic'],
    'extra-bold-italic': ['font-extrabold', 'italic'],
    'black-italic': ['font-black', 'italic'],
};
