export const fontWeights = {
    thin: ['font-thin'],
    extralight: ['font-extralight'],
    light: ['font-light'],
    regular: ['font-normal'],
    medium: ['font-medium'],
    semibold: ['font-semibold'],
    bold: ['font-bold'],
    extrabold: ['font-extrabold'],
    black: ['font-black'],
    thinitalic: ['font-thin', 'italic'],
    extralightitalic: ['font-extralight', 'italic'],
    lightitalic: ['font-light', 'italic'],
    italic: ['font-normal', 'italic'],
    regularitalic: ['font-normal', 'italic'],
    mediumitalic: ['font-medium', 'italic'],
    semibolditalic: ['font-semibold', 'italic'],
    bolditalic: ['font-bold', 'italic'],
    extrabolditalic: ['font-extrabold', 'italic'],
    blackitalic: ['font-black', 'italic'],
};
